*===================================================
*Labelling occupational classification
*===================================================

label define isco88lbl ///
	3131 "PHOTOGR,IMAGE,SOUND REC EQUIPMENT OPER" ///
9162 "SWEEPERS AND RELATED LABOURERS" ///
8124 "METAL DRAWERS AND EXTRUDERS" ///
8324 "HEAVY TRUCK AND LORRY DRIVERS" ///
6141 "FORESTRY WORKERS AND LOGGERS" ///
3118 "DRAUGHTSPERSONS" ///
8131 "GLASS AND CERAMICS KILN AND RELATED MACHINE OPERATORS" ///
8253 "PAPER-PRODUCTS MACHINE OPERATORS" ///
3417 "APPRAISERS, VALUERS AND AUCTIONEERS" ///
4190 "OTHER OFFICE CLERKS" ///
2332 "PRE-PRIMARY EDUC TEACHING PROFESSIONALS" ///
8100 "STATIONARY PLANT AND RELATED OPERATORS" ///
2429 "LEGAL PROF NOT ELSEWHERE CLASSIFIED" ///
2224 "PHARMACISTS" ///
9100 "SALES AND SERVICES ELEMENTARY OCCUPATIONS" ///
7139 "BUILDING FINISHERS AND RELATED TRADE WORKERS NEC" ///
4214 "PAWNBROKERS AND MONEY-LENDERS" ///
8251 "PRINTING-MACHINE OPERATORS" ///
3422 "CLEARING AND FORWARDING AGENTS" ///
2100 "PHYS, MATHEM, ENGIN SCIENCE PROFESSIONALS" ///
3144 "AIR TRAFFIC CONTROLLERS" ///
9310 "MINING AND CONSTRUCTION LABOURERS" ///
7433 "TAILORS, DRESSMAKERS AND HATTERS" ///
7343 "PRINTING ENGRAVERS AND ETCHERS" ///
9151 "MESSENGERS, PACKAGE AND LUGGAGE PORTERS AND DELIVERERS" ///
2110 "PHYSICS, CHEMISTS, RELATED PROFESSIONALS" ///
2111 "PHYSICISTS AND ASTRONOMERS" ///
2112 "METEOROLOGISTS" ///
2113 "CHEMISTS" ///
2114 "GEOLOGISTS AND GEOPHYSICISTS" ///
4221 "TRAVEL AGENCY AND RELATED CLERKS" ///
8321 "MOTORCYCLE DRIVERS" ///
2120 "MATHEM, STAT, RELATED PROFESSIONALS" ///
2121 "MATHEMATICIANS AND RELATED PROFESSIONALS" ///
2122 "STATISTICIANS" ///
3100 "PHYSICAL,ENGINEERING SCIENCE ASSOCIATE PROF" ///
8284 "METAL-, RUBBER- AND PLASTIC-PRODUCTS ASSEMBLERS" ///
2400 "OTHER PROFESSIONALS" ///
7340 "CRAFT PRINTING AND RTW" ///
2130 "COMPUTING PROFESSIONALS" ///
2131 "COMPUTER SYSTEMS DESIGNERS,ANALYSTS,PROGRAMMERS" ///
1110 "LEGISLATORS, SENIOR GOVERNMENT OFFICIALS" ///
2139 "COMPUTER PROFESSIONALS NEC" ///
2140 "ARCHITECTS,ENGINEERS,RELATED PROFESSIONALS" ///
2141 "ARCHITECTS, TOWN AND TRAFFIC PLANNERS" ///
2142 "CIVIL ENGINEERS" ///
2143 "ELECTRICAL ENGINEERS" ///
2144 "ELECTRONICS, TELECOMMUNICATIONS ENGINEERS" ///
7111 "MINERS AND QUARRY WORKERS" ///
2146 "CHEMICAL ENGINEERS" ///
2147 "MINING ENGINEERS, METALL,REL PROFESSIONALS" ///
100 "ARMED FORCES" ///
2149 "ARCHITECTURE, ENGINEERING REL PROF NEC" ///
3212 "AGRONOMY AND FORESTRY TECHNICIANS" ///
6153 "DEEP-SEA FISHERY WORKERS" ///
3310 "PRIMARY EDUCATION TEACHING ASSOCIATE PROF" ///
8143 "PAPERMAKING-PLANT OPERATORS" ///
5123 "WAITERS, WAITRESSES AND BARTENDERS" ///
8152 "CHEMICAL-HEAT-TREATING-PLANT OPERATORS" ///
3450 "POLICE INSPECTORS AND DETECTIVES" ///
6122 "POULTRY PRODUCERS" ///
9132 "HELPERS AND CLEANERS IN OFFICES, HOTELS AND OTHER ESTABLISHMENTS" ///
7216 "UNDERWATER WORKERS" ///
1140 "SENIOR OFFICIALS OF SPECIAL-INTEREST ORG" ///
1141 "SENIOR OFFICIALS OF POLITICAL-PARTY ORG" ///
1142 "SENIOR OFFICIALS OF ECONOMIC-INTEREST ORG" ///
1143 "SENIOR OFF HUMAN, SPECIAL-INTEREST ORG" ///
7313 "JEWELLERY AND PRECIOUS-METAL WORKERS" ///
7440 "PELT, LEATHER AND SHOEMAKING TRADES WORKERS" ///
3412 "INSURANCE REPRESENTATIVES" ///
8240 "WOOD-PRODUCTS MACHINE OPERATORS" ///
8000 "PLANT AND MACHINE OPERATORS AND ASSEMBLERS" ///
5133 "HOME-BASED PERSONAL CARE WORKERS" ///
7123 "CONCRETE PLACERS, CONCRETE FINISHERS AND RELATED WORKERS" ///
8222 "AMMUNITION- AND EXPLOSIVE-PRODUCTS MACHINE OPERATORS" ///
2420 "LEGAL PROFESSIONALS" ///
3300 "TEACHING ASSOCIATE PROFESSIONALS" ///
7220 "BLACKSMITHS, TOOL-MAKERS AND RELATED TRADES WORKERS" ///
2200 "LIFE SCIENCE AND HEALTH PROFESSIONALS" ///
8250 "PRINTING-, BINDING- AND PAPER-PRODUCTS MACHINE OPERATORS" ///
4144 "SCRIBES AND RELATED WORKERS" ///
3141 "SHIPS' ENGINEERS" ///
7212 "WELDERS AND FLAME CUTTERS" ///
2210 "LIFE SCIENCE PROFESSIONALS" ///
2211 "BIOL,BOTAN,ZOOL AND RELATED PROFESSIONALS" ///
2212 "PHARM, PATHOL AND RELATED PROFESSIONALS" ///
2213 "AGRONOMISTS AND RELATED PROFESSIONALS" ///
8151 "CRUSHING-, GRINDING- AND CHEMICAL-MIXING-MACHINERY OPERATORS" ///
1233 "SALES AND MARKETING MANAGERS" ///
1223 "MANAGERS IN CONSTRUCTION" ///
2220 "HEALTH PROFESSIONALS (EXCEPT NURSING)" ///
2221 "MEDICAL DOCTORS" ///
2222 "DENTISTS" ///
2223 "VETERINARIANS" ///
2470 "PUBLIC SERVICE ADMINISTRATIVE PROFESSIONALS" ///
7224 "METAL WHEEL-GRINDERS, POLISHERS AND TOOL SHARPENERS" ///
2229 "HEALTH PROF (NOT NURSING) NOT ELSEW CLASS" ///
2230 "NURSING AND MIDWIFERY PROFESSIONALS" ///
7321 "ABRASIVE WHEEL FORMERS, POTTERS AND RELATED WORKERS" ///
1210 "DIRECTORS AND CHIEF EXECUTIVES" ///
3222 "HYGIENISTS, HEALTH ENVIRONMENTAL OFFICERS" ///
3143 "AIRCRAFT PILOTS, RELATED ASSOCIATED PROF" ///
1227 "MANAGERS IN BUSINESS SERVICES ENTERPRISES" ///
1220 "PRODUCTION AND OPERATIONS MANAGERS" ///
1221 "MANAGERS AGRICULTURE,HUNTING,FORESTRY,FISHING" ///
1222 "MANAGERS IN MANUFACTURING" ///
8278 "BREWERS, WINE AND OTHER BEVERAGE MACHINE OPERATORS" ///
1224 "MANAGERS IN WHOLESALE AND RETAIL TRADE" ///
1225 "MANAGERS IN RESTAURANTS AND HOTELS" ///
1226 "MANAGERS TRANSPORT,STORAGE,COMMUNICATIONS" ///
1200 "CORPORATE MANAGERS" ///
1228 "MANAGERS PERSONAL CARE,CLEANING,REL SERV" ///
1229 "MANAGERS NEC" ///
1230 "OTHER SPECIALIST MANAGERS" ///
5110 "TRAVEL ATTENDANTS AND RELATED WORKERS" ///
3432 "LEGAL RELATED BUSINESS ASSOCIATE PROF" ///
7100 "EXTRACTION AND BUILDING TRADES WORKERS" ///
1234 "ADVERTISING AND PUBLIC RELATIONS MANAGERS" ///
1235 "SUPPLY AND DISTRIBUTION  MANAGERS" ///
8229 "CHEMICAL-PRODUCTS MACHINE OPERATORS NEC" ///
1237 "RESEARCH AND DEVELOPMENT MANAGERS" ///
1239 "OTHER SPEC MANAGERS NEC" ///
2351 "EDUCATION METHODS SPECIALISTS" ///
8142 "PAPER-PULP PLANT OPERATORS" ///
1231 "FINANCE AND ADMINISTRATION  MANAGERS" ///
3145 "AIR TRAFFIC SAFETY TECHNICIANS" ///
1232 "PERSONNEL AND INDUSTRIAL RELATIONS MANAGERS" ///
10000 "NO MATCH" ///
4121 "ACCOUNTING AND BOOKKEEPING CLERKS" ///
7112 "SHOTFIRERS AND BLASTERS" ///
7135 "GLAZIERS" ///
3229 "HEALTH ASS PROF EXCPT NURSING NOT ELSE CLASS" ///
3114 "ELECTRONICS,TELECOM ENGINEERING TECHNICIANS" ///
7232 "AIRCRAFT ENGINE MECHANICS AND FITTERS" ///
5141 "HAIRDRESS,BARBER,BEAUTICIAN, RELATED WORKERS" ///
8312 "RAILWAY BRAKERS, SIGNALLERS AND SHUNTERS" ///
8334 "LIFTING-TRUCK OPERATORS" ///
1236 "COMPUTING SERVICES MANAGERS" ///
8111 "MINING PLANT OPERATORS" ///
6140 "FORESTRY AND RELATED WORKERS" ///
8265 "FUR- AND LEATHER-PREPARING-MACHINE OPERATORS" ///
3211 "LIFE SCIENCE TECHNICIANS" ///
5149 "OTHER PERSONAL SERVICES WORKERS NEC" ///
8210 "METAL- AND MINERAL-PRODUCTS MACHINE OPERATORS" ///
8163 "INCINERATOR, WATER-TREATMENT AND RELATED PLANT OPERATORS" ///
8223 "METAL FINISHING-, PLATING- AND COATING-MACHINE OPERATORS" ///
8272 "DAIRY-PRODUCTS MACHINE OPERATORS" ///
6142 "CHARCOAL BURNERS AND RELATED WORKERS" ///
2412 "PERSONNEL AND CAREERS PROFESSIONALS" ///
7241 "ELECTRICAL MECHANICS FITTERS AND SERVICES" ///
1300 "MANAGERS OF SMALL ENTERPRISES" ///
3433 "BOOKKEEPERS" ///
6111 "FIELD CROP AND VEGETABLE GROWERS" ///
9110 "STREET VENDORS AND RELATED WORKERS" ///
3414 "TRAVEL CONSULTANTS AND ORGANISERS" ///
1310 "MANAGERS OF SMALL ENTERPRISES" ///
1311 "MANAGERS OF SMALL ENTERPRISES IN AGR,HUNTING,FORESTRY,FISHING" ///
2445 "PSYCHOLOGISTS" ///
7430 "TEXTILE, GARMENT AND RELATED TRADES WORKERS" ///
1314 "MANAGERS OF SMALL ENTERPRISES IN WHOLESALE AND RETAIL TRADE" ///
1315 "MANAGERS OF SMALL ENTERPRISES OF RESTAURANTS AND HOTELS" ///
1316 "MANAGERS OF SMALL ENTERPRISES IN TRANSP,STORAGE,COMM" ///
8286 "PAPERBOARD, TEXTILE AND RELATED PRODUCTS ASSEMBLERS" ///
1318 "MANAGERS OF SMALL ENTERPRISES IN PERS CARE,CLEANING,REL SERV" ///
1319 "MANAGERS OF SMALL ENTERPRISES NEC" ///
7143 "BUILDING STRUCTURE CLEANERS" ///
2331 "PRIMARY EDUCATION TEACHING PROFESSIONALS" ///
2422 "JUDGES" ///
5122 "COOKS" ///
2350 "OTHER TEACHING PROFESSIONALS" ///
7240 "ELECTRICAL AND ELECTRONIC EQUIPMENT MECHANICS AND FITTERS" ///
3113 "ELECTRICAL ENGINEERING TECHNICIANS" ///
3471 "DECORATORS AND COMMERCIAL DESIGNERS" ///
3230 "NURSING MIDWIFERY ASSOCIATE PROF" ///
8224 "PHOTOGRAPHIC-PRODUCTS MACHINE OPERATORS" ///
4133 "TRANSPORT CLERKS" ///
8323 "BUS AND TRAM DRIVERS" ///
6150 "FISHERY WORKERS, HUNTERS AND TRAPPERS" ///
3440 "CUSTOM,TAX,RELATED GOV ASSOCIATE PROF" ///
8140 "WOOD-PROCESSING- AND PAPERMAKING-PLANT OPERATORS" ///
8261 "FIBRE-PREPARING-, SPINNING- AND WINDING-MACHINE OPERATORS" ///
7213 "SHEET-METAL WORKERS" ///
3224 "OPTOMETRISTS AND OPTICIANS" ///
3473 "STREET,NIGHTCLUB,REL MUSICIANS,SINGERS,DANCE" ///
7332 "HANDICRAFT WORKERS IN TEXTILE, LEATHER AND RELATED MATERIALS" ///
7344 "PHOTOGRAPHIC AND RELATED WORKERS" ///
9161 "GARBAGE COLLECTORS" ///
2410 "BUSINESS PROFESSIONALS" ///
5161 "FIRE-FIGHTERS" ///
6130 "CROP AND ANIMAL PRODUCERS" ///
4140 "LIBRARY, MAIL AND RELATED CLERKS" ///
4222 "RECEPTIONISTS AND INFORMATION CLERKS" ///
8331 "MOTORISED FARM AND FORESTRY PLANT OPERATORS" ///
6154 "HUNTERS AND TRAPPERS" ///
3122 "COMPUTER EQUIPMENT OPERATORS" ///
7120 "BUILDING FRAME AND RELATED TRADES WORKERS" ///
8269 "TEXTILE-, FUR- AND LEATHER-PRODUCTS MACHINE OPERATORS NEC" ///
7230 "MACHINERY MECHANICS AND FITTERS" ///
8252 "BOOK-BINDING-MACHINE OPERATORS" ///
7345 "BOOKBINDERS AND RELATED WORKERS" ///
9130 "DOMESTIC AND RELATED HELPERS, CLEANERS AND LAUNDERERS" ///
2451 "AUTHORS, JOURNALISTS AND OTHER WRITERS" ///
7442 "SHOE-MAKERS AND RELATED WORKERS" ///
3110 "PHYSICAL,ENGINEERING SCIENCE TECHNICIANS" ///
9213 "FISHERY, HUNTING AND TRAPPING LABOURERS" ///
4141 "LIBRARY AND FILING CLERKS" ///
7434 "FURRIERS AND RELATED WORKERS" ///
7411 "BUTCHERS, FISHMONGERS AND RELATED FOOD PREPARERS" ///
8320 "MOTOR VEHICLE DRIVERS" ///
2455 "FILM, STAGE AND RELATED ACTORS AND DIRECTORS" ///
4110 "SECRETARIES AND KEYBOARD-OPERATING CLERKS" ///
3444 "GOVERNMENT LICENSING OFFICIALS" ///
7124 "CARPENTERS AND JOINERS" ///
8277 "TEA-, COFFEE- AND COCOA-PROCESSING-MACHINE OPERATORS" ///
3420 "BUSINESS SERVICES AGENTS AND TRADE BROKERS" ///
9142 "VEHICLE, WINDOW AND RELATED CLEANERS" ///
7221 "BLACKSMITHS, HAMMER-SMITHS AND FORGING-PRESS WORKERS" ///
2330 "PRIMARY AND PRE-PRIMARY EDUC TEACHING PROF" ///
5200 "MODELS, SALESPERSONS AND DEMONSTRATORS" ///
2453 "COMPOSERS, MUSICIANS AND SINGERS" ///
7441 "PELT DRESSERS, TANNERS AND FELLMONGERS" ///
3431 "ADM SECRETARIES, RELATED ASSOCIATE PROF" ///
5169 "PROTECTIVE SERVICES WORKERS NEC" ///
3340 "OTHER TEACHING ASSOCIATE PROFESSIONALS" ///
7415 "FOOD AND BEVERAGE TASTERS AND GRADERS" ///
8280 "ASSEMBLERS" ///
1312 "MANAGERS OF SMALL ENTERPRISES IN MANUFACTURING" ///
4114 "CALCULATING-MACHINE OPERATORS" ///
9212 "FORESTRY LABOURERS" ///
7000 "CRAFTS AND RELATED TRADES WORKERS" ///
8285 "WOOD AND RELATED PRODUCTS ASSEMBLERS" ///
4211 "CASHIERS AND TICKET CLERKS" ///
9150 "MESSENGERS, PORTERS, DOORKEEPERS AND RELATED WORKERS" ///
8121 "ORE AND METAL FURNACE OPERATORS" ///
7130 "BUILDING FINISHERS AND RELATED TRADES WORKERS" ///
3416 "BUYERS" ///
5000 "SERVICE WORKERS,SHOP, MARKET SALES WORKERS" ///
6100 "SKILLED AGRICULTURAL AND FISHERY WORKERS" ///
3223 "DIETICIANS AND NUTRITIONISTS" ///
7322 "GLASS-MAKERS, CUTTERS, GRINDERS AND FINISHERS" ///
5121 "HOUSEKEEPERS AND RELATED WORKERS" ///
2443 "PHILOSOPHERS,HISTORIANS,POLITICAL SCIENTISTS" ///
1100 "LEGISLATORS AND SENIOR OFFICIALS" ///
5142 "COMPANIONS AND VALETS" ///
3320 "PRE-PRIMARY EDU TEACHING ASSOCIATE PROF" ///
7132 "FLOOR LAYERS AND TILE SETTERS" ///
4215 "DEBT-COLLECTORS AND RELATED WORKERS" ///
8231 "RUBBER-PRODUCTS MACHINE OPERATORS" ///
7242 "ELECTRONICS MECHANICS, FITTERS AND SERVICERS" ///
3225 "DENTAL ASSISTANTS" ///
8232 "PLASTIC-PRODUCTS MACHINE OPERATORS" ///
8266 "SHOEMAKING- AND RELATED MACHINE OPERATORS" ///
7423 "WOODWORKING MACHINE SETTERS AND SETTER-OPERATORS" ///
3442 "GOVERNMENT TAX AND EXCISE OFFICIALS" ///
9131 "DOMESTIC HELPERS AND CLEANERS" ///
4122 "STATISTICAL AND FINANCE CLERKS" ///
3130 "OPTICAL AND ELECTRONIC EQUIPMENT OPERATORS" ///
8160 "POWER-PRODUCTION AND RELATED PLANT OPERATORS" ///
2310 "COLL,UNIV, HIGHER EDUC TEACHING PROF" ///
8153 "CHEMICAL-FILTERING- AND SEPARATING-EQUIPMENT OPERATORS" ///
7233 "AGRICULTURAL- OR INDUSTRIAL-MACHINERY MECHANICS AND FITTERS" ///
2450 "WRITERS AND CREATIVE OR PERFORMING ARTISTS" ///
2432 "LIBRARIANS,RELATED INFORMATION PROF" ///
3226 "PHYSIOTHERAPISTS AND REL ASSOCIATE PROF" ///
8162 "STEAM-ENGINE AND BOILER OPERATORS" ///
3227 "VETERINARY ASSISTANTS" ///
7330 "HANDICRAFT WORKERS IN WOOD, TEXTILE, LEATHER AND RELATED MATERIALS" ///
2460 "RELIGIOUS PROFESSIONALS" ///
7341 "COMPOSITORS, TYPESETTERS AND RELATED WORKERS" ///
8274 "BAKED-GOODS, CEREAL- AND CHOCOLATE-PRODUCTS MACHINE OPERATORS" ///
7310 "PRECISION WORKERS IN METAL AND RELATED MATERIALS" ///
9153 "VENDING-MACHINE MONEY COLLECTORS, METER READERS AND RELATED WORKERS" ///
3152 "SAFETY, HEALTH AND QUALITY INSPECTORS" ///
8212 "CEMENT AND OTHER MINERAL PRODUCTS MACHINE OPERATORS" ///
7140 "PAINTERS, BUILDING STRUCTURE CLEANERS AND RTW" ///
4223 "TELEPHONE SWITCHBOARD OPERATORS" ///
3150 "SAFETY AND QUALITY INSPECTORS" ///
6112 "GARDENERS, HORTICULTURAL AND NURSERY GROWERS" ///
3421 "TRADE BROKERS" ///
8112 "MINERAL-ORE AND STONE-PROCESSING-PLANT OPERATORS" ///
3430 "ADMINISTRATIVE ASSOCIATE PROFESSIONALS" ///
3112 "CIVIL ENGINEERING TECHNICIANS" ///
3423 "EMPLOYMENT AGENTS AND LABOUR CONTRACTORS" ///
8282 "ELECTRICAL-EQUIPMENT ASSEMBLERS" ///
7431 "FIBRE PREPARERS" ///
3411 "SECURITIES AND FINANCE DEALERS AND BROKERS" ///
4130 "MATERIAL-RECORDING AND TRANSPORT CLERKS" ///
2430 "ARCHIV,LIBR,RELATED INFORMATION PROF" ///
7400 "OTHER CRAFT AND RELATED TRADES WORKERS" ///
5111 "TRAVEL ATTENDANTS AND TRAVEL STEWARDS" ///
7113 "STONE SPLITTERS, CUTTERS AND CARVERS" ///
2419 "BUSINESS PROF NEC" ///
7324 "GLASS, CERAMICS AND RELATED DECORATIVE PAINTERS" ///
5220 "SHOP, STALL AND MARKET SALESPERSONS AND DEMONSTRATORS" ///
3231 "NURSING ASSOCIATE PROFESSIONALS" ///
7210 "METAL MOULDERS, WELDERS, SHEET-METAL WORKERS, STRUCTURAL-METAL PREPARERS, AND RTW" ///
9000 "ELEMENTARY OCCUPATIONS" ///
2145 "MECHANICAL ENGINEERS" ///
8290 "OTHER MACHINE OPERATORS NEC" ///
7435 "TEXTILE, LEATHER AND RELATED PATTERN-MAKERS AND CUTTERS" ///
3475 "ATHLETES,SPORTSPERS, RELATED ASSOCIATE PROF" ///
3200 "LIFE,SCIENCE AND HEALTH ASSOCIATE PROF" ///
6151 "AQUATIC LIFE CULTIVATION WORKERS" ///
2148 "CARTOGRAPHERS AND SURVEYORS" ///
8263 "SEWING-MACHINE OPERATORS" ///
7134 "INSULATION WORKERS" ///
6120 "ANIMAL PRODUCERS AND RELATED WORKERS" ///
7437 "UPHOLSTERERS AND RELATED WORKERS" ///
7414 "FRUIT, VEGETABLE AND RELATED PRESERVERS" ///
2431 "ARCHIVISTS AND CURATORS" ///
7311 "PRECISION-INSTRUMENT MAKERS AND REPAIRERS" ///
4113 "DATA ENTRY OPERATORS" ///
3221 "MEDICAL ASSISTANTS" ///
5162 "POLICE OFFICERS" ///
3330 "SPECIAL EDUCATION TEACHING ASSOCIATE PROF" ///
8264 "BLEACHING-, DYEING- AND CLEANING-MACHINE OPERATORS" ///
8333 "CRANE, HOIST AND RELATED PLANT OPERATORS" ///
5131 "CHILD-CARE WORKERS" ///
7121 "BUILDERS" ///
3151 "BUILDING AND FIRE INSPECTORS" ///
8271 "MEAT- AND FISH-PROCESSING-MACHINE OPERATORS" ///
5100 "PERSONAL AND PROTECTIVE SERVICES WORKERS" ///
9111 "STREET VENDORS" ///
7346 "SILK-SCREEN, BLOCK AND CRAFT TEXTILE PRINTERS" ///
1317 "MNGR SMALL ENT OF BUSINESS SERV ENTERPR" ///
9330 "TRANSPORT LABOURERS AND FREIGHT HANDLERS" ///
9210 "AGRICULTURAL, FISHERY AND RELATED LABOURERS" ///
7245 "ELECTRICAL LINE INSTALLERS, REPAIRERS AND CABLE JOINTERS" ///
4142 "MAIL CARRIERS AND SORTING CLERKS" ///
3460 "SOCIAL WORK ASSOCIATE PROFESSIONALS" ///
7412 "BAKERS, PASTRY-COOKS AND CONFECTIONERY MAKERS" ///
3132 "BROADCASTING,TELECOM EQUIPMENT OPERATORS" ///
4111 "STENOGRAPHERS AND TYPISTS" ///
5139 "PERSONAL CARE,RELATED WORKERS NOT ELSE CLASS" ///
2452 "SCULPTORS, PAINTERS AND RELATED ARTISTS" ///
8279 "TOBACCO PRODUCTION MACHINE OPERATORS" ///
3228 "PHARMACEUTICAL ASSISTANTS" ///
3429 "BUSINES,SERV,AGNTS,TRDE BROKR NOT ELSE CLASS" ///
7222 "TOOL-MAKERS AND RELATED WORKERS" ///
2441 "ECONOMISTS" ///
3142 "SHIPS' DECK OFFICERS AND PILOTS" ///
7416 "TOBACCO PREPARERS AND TOBACCO PRODUCTS MAKERS" ///
4115 "SECRETARIES" ///
3470 "ARTISTIC,ENTERTAINMENT,SPORTS ASSOCIATE PROF" ///
7129 "BUILDING FRAME AND RELATED TRADES WORKERS NEC" ///
4132 "PRODUCTION CLERKS" ///
8287 "COMPOSITE PRODUCTS ASSEMBLERS" ///
4212 "TELLERS AND OTHER COUNTER CLERKS" ///
8170 "INDUSTRIAL ROBOT OPERATORS" ///
8122 "METAL MELTERS, CASTERS AND ROLLING-MILL OPERATORS" ///
1313 "MANAGERS OF SMALL ENTERPRISES IN CONSTRUCTION" ///
8322 "CAR, TAXI AND VAN DRIVERS" ///
7323 "GLASS ENGRAVERS AND ETCHERS" ///
3413 "ESTATE AGENTS" ///
9312 "CONSTRUCTION AND MAINTENANCE LABOURERS: ROADS, DAMS, AND SIMILAR CONSTRUCTION" ///
2300 "TEACHING PROFESSIONALS" ///
8260 "TEXTILE-, FUR- AND LEATHER-PRODUCTS MACHINE OPERATORS" ///
7420 "WOOD TREATERS, CABINET-MAKERS AND RTW" ///
2440 "SOCIAL SCIENCE AND RELATED PROFESSIONALS" ///
8161 "POWER-PRODUCTION PLANT OPERATORS" ///
5143 "UNDERTAKERS AND EMBALMERS" ///
7133 "PLASTERERS" ///
7122 "BRICKLAYERS AND STONEMASONS" ///
5112 "TRANSPORT CONDUCTORS" ///
9160 "GARBAGE COLLECTORS AND RELATED LABOURERS" ///
2000 "PROFESSIONALS" ///
7131 "ROOFERS" ///
5160 "PROTECTIVE SERVICES WORKERS" ///
8330 "AGRICULTURAL AND OTHER MOBILE PLANT OPERATORS" ///
3000 "TECHNICIANS AND ASSOCIATE PROFESSIONALS" ///
3210 "LIFE,SCIENCE TECHN AND REL ASSOCIATE PROF" ///
7424 "BASKETRY WEAVERS, BRUSH MAKERS AND RELATED WORKERS" ///
3140 "SHIP, AIRCRAFT CONTROLLERS AND TECHNICIANS" ///
9133 "HAND-LAUNDERERS AND PRESSERS" ///
8141 "WOOD-PROCESSING-PLANT OPERATORS" ///
6000 "SKILLED AGRICULTURAL AND FISHERY WORKERS" ///
7137 "BUILDING AND RELATED ELECTRICIANS" ///
6121 "DAIRY AND LIVESTOCK PRODUCERS" ///
4220 "CLIENT INFORMATION CLERKS" ///
3115 "MECHANICAL ENGINEERING TECHNICIANS" ///
8130 "GLASS, CERAMICS AND RELATED PLANT OPERATORS" ///
8310 "LOCOMOTIVE ENGINE DRIVERS AND RELATED WORKERS" ///
7331 "HANDICRAFT WORKERS IN WOOD AND RELATED MATERIALS" ///
8275 "FRUIT-, VEGETABLE- AND NUT-PROCESSING-MACHINE OPERATORS" ///
2444 "PHILOLOGISTS, TRANSLATORS AND INTERPRETERS" ///
7300 "PRECISION, HANDICRAFT, CRAFT PRINTING AND RTW" ///
9141 "BUILDING CARETAKERS" ///
7141 "PAINTERS AND RELATED WORKERS" ///
8311 "LOCOMOTIVE ENGINE DRIVERS" ///
8159 "CHEMICAL-PROCESSING-PLANT OPERATORS NEC" ///
5120 "HOUSEKEEPING, RESTAURANT SERVICES WORKERS" ///
3117 "MINING AND METALLURGICAL TECHNICIANS" ///
7110 "MINERS, SHOTFIRERS, STONE CUTTERS AND CARVERS" ///
8220 "CHEMICAL-PRODUCTS MACHINE OPERATORS" ///
2352 "SCHOOL INSPECTORS" ///
9211 "FARM-HANDS AND LABOURERS" ///
7214 "STRUCTURAL-METAL PREPARERS AND ERECTORS" ///
2446 "SOCIAL WORK PROFESSIONALS" ///
7432 "WEAVERS, KNITTERS AND RELATED WORKERS" ///
4131 "STOCK CLERKS" ///
4100 "OFFICE CLERKS" ///
3119 "PHYS, ENGIN SCIENCE TECHN NOT ELSEW CLASS" ///
3133 "MEDICAL EQUIPMENT OPERATORS" ///
9140 "BUILDING CARETAKERS, WINDOW AND RELATED CLEANERS" ///
8120 "METAL-PROCESSING PLANT OPERATORS" ///
7211 "METAL MOULDERS AND COREMAKERS" ///
8113 "WELL DRILLERS AND BORERS AND RELATED WORKERS" ///
3121 "COMPUTER ASSISTANTS" ///
2320 "SECONDARY EDUCATION TEACHING PROFESSIONALS" ///
7436 "SEWERS, EMBROIDERERS AND RELATED WORKERS" ///
8230 "RUBBER- AND PLASTIC-PRODUCTS MACHINE OPERATORS" ///
3472 "RADIO, TELEVISION AND OTHER ANNOUNCERS" ///
8276 "SUGAR PRODUCTION MACHINE OPERATORS" ///
6152 "INLAND AND COASTAL WATERS FISHERY WORKERS" ///
3441 "CUSTOMS AND BORDER INSPECTORS" ///
7410 "FOOD PROCESSING AND RTW" ///
8200 "MACHINE OPERATORS AND ASSEMBLERS" ///
2340 "SPECIAL EDUCATION TEACHING PROFESSIONALS" ///
4000 "CLERKS" ///
8139 "GLASS, CERAMICS AND RELATED PLANT OPERATORS NEC" ///
3434 "STATISTICAL, MATHEMAT REL ASSOCIATE PROF" ///
3116 "CHEMICAL ENGINEERING TECHNICIANS" ///
8283 "ELECTRONIC-EQUIPMENT ASSEMBLERS" ///
7215 "RIGGERS AND CABLE SPLICERS" ///
5130 "PERSONAL CARE AND RELATED WORKERS" ///
3415 "TECHNICAL AND COMMERCIAL SALES REP" ///
9320 "MANUFACTURING LABOURERS" ///
3410 "FINANCE AND SALES ASSOCIATE PROFESSIONALS" ///
7312 "MUSICAL-INSTRUMENT MAKERS AND TUNERS" ///
2442 "SOCIOLOGISTS, ANTHROPOLOGISTS, REL PROF" ///
5163 "PRISON GUARDS" ///
5132 "INSTITUTION-BASED PERSONAL CARE WORKERS" ///
9200 "AGRICULTURAL, FISHERY AND RELATED LABOURERS" ///
9152 "DOORKEEPERS, WATCHPERSONS AND RELATED WORKERS" ///
9311 "MINING AND QUARRYING LABOURERS" ///
8273 "GRAIN- AND SPICE-MILLING-MACHINE OPERATORS" ///
4210 "CASHIERS, TELLERS AND RELATED CLERKS" ///
8300 "DRIVERS AND MOBILE PLANT OPERATORS" ///
8211 "MACHINE-TOOL OPERATORS" ///
3220 "HEALTH ASSOCIATE PROF (EXCEPT NURSING)" ///
8340 "SHIPS' DECK CREWS AND RELATED WORKERS" ///
4143 "CODING, PROOF-READING AND RELATED CLERKS" ///
7413 "DAIRY-PRODUCTS WORKERS" ///
3123 "INDUSTRIAL ROBOT CONTROLLERS" ///
3139 "OPTICAL,ELECTR EQUIPM OPER NOT ELSEW CLASS" ///
4112 "WORD-PROCESSOR AND RELATED OPERATORS" ///
2421 "LAWYERS" ///
8150 "CHEMICAL-PROCESSING-PLANT OPERATORS" ///
8281 "MECHANICAL-MACHINERY ASSEMBLERS" ///
7422 "CABINETMAKERS AND RELATED WORKERS" ///
6129 "ANIMAL PRODUCERS AND RELATED WORKERS NEC" ///
9113 "DOOR-TO-DOOR AND TELEPHONE SALESPERSONS" ///
7223 "MACHINE-TOOL SETTERS AND SETTER-OPERATORS" ///
2454 "CHOREOGRAPHERS AND DANCERS" ///
7320 "POTTERS, GLASS-MAKERS AND RTW" ///
9120 "SHOE CLEANING AND OTHER STREET SERVICES ELEMENTARY OCCUPATIONS" ///
2411 "ACCOUNTANTS" ///
3120 "COMPUTER ASSOCIATE PROFESSIONALS" ///
5140 "OTHER PERSONAL SERVICES WORKERS" ///
2359 "OTHER TEACHING PROF NEC" ///
8154 "CHEMICAL-STILL AND REACTOR OPERATORS (EXCEPT PETROLEUM AND NATURAL GAS)" ///
9313 "BUILDING CONSTRUCTION LABOURERS" ///
4213 "BOOKMAKERS AND CROUPIERS" ///
8123 "METAL HEAT-TREATING-PLANT OPERATORS" ///
7342 "STEREOTYPERS AND ELECTROTYPERS" ///
3480 "RELIGIOUS ASSOCIATE PROFESSIONALS" ///
8110 "MINING AND MINERAL-PROCESSING-PLANT OPERATORS" ///
3213 "FARMING AND FORESTRY ADVISERS" ///
3111 "CHEMICAL AND PHYSICAL SCIENCE TECHNICIANS" ///
8262 "WEAVING- AND KNITTING-MACHINE OPERATORS" ///
7421 "WOOD TREATERS" ///
9300 "LABOURERS IN MINING, CONSTRUCTION, MANUFACTURING AND TRANSPORT" ///
3419 "FINANCE,SALES ASSOCIATE PROF NOT ELSE CLASS" ///
7136 "PLUMBERS AND PIPE FITTERS" ///
4120 "NUMERICAL CLERKS" ///
3449 "CUSTOM,TAX,REL GOV ASSOC PROF NOT ELSE CLASS" ///
3232 "MIDWIFERY ASSOCIATE PROFESSIONALS" ///
7244 "TELEGRAPH AND TELEPHONE INSTALLERS AND SERVICERS" ///
8155 "PETROLEUM- AND NATURAL-GAS-REFINING-PLANT OPERATORS" ///
5113 "TRAVEL GUIDES" ///
1000 "LEGISLATORS, SENIOR OFFICIALS AND MANAGERS" ///
7231 "MOTOR VEHICLE MECHANICS AND FITTERS" ///
3443 "GOVERNMENT SOCIAL BENEFITS OFFICIALS" ///
5210 "FASHION AND OTHER MODELS" ///
8332 "EARTH-MOVING AND RELATED PLANT OPERATORS" ///
7200 "METAL, MACHINERY AND RELATED TRADES WORKERS" ///
4200 "CUSTOMER SERVICES CLERKS" ///
8270 "FOOD AND RELATED PRODUCTS MACHINE OPERATORS" ///
3474 "CLOWNS,MAGICIANS,ACROBATS, REL ASSOCIATE PROF" ///
6110 "MARKET GARDENERS AND CROP GROWERS" ///
3400 "OTHER ASSOCIATE PROFESSIONALS" ///
8221 "PHARMACEUTICAL-AND TOILETRY-PRODUCTS MACHINE OPERATORS" 

label values isco88 isco88lbl

label define educationLbl ///
1 "NONE/ NO QUALIFICATIONS" ///
2 "GCSE D-G/ CSE BELOW GRADE 1/ GNVQ FOUNDATION" ///
3 "GCSE A*-C/ GNVQ INTERMEDIATE/ GCE 'O' LEVEL/ CSE GRADE 1/ SC" ///
4 "GCE 'A' LEVEL/ GNVQ ADVANCED" ///
5 "SCE STANDARD (4-7)/ ORDINARY (BELOW C)" ///
6 "SCE STANDARD (1-3)/ ORDINARY (A-C) OR SLC/SUPE LOWER" ///
7 "SCE HIGHER OR SLC/SUPE HIGHER" ///
8 "CERTIFICATE OF SIXTH YEAR STUDIES" ///
9 "NVQ LEVEL 1 (OR SNVQ 1)" ///
10 "NVQ LEVEL 2 (OR SNVQ 2)" ///
11 "NVQ LEVEL 3 (OR SNVQ 3) OR ONC/OND (OR SNC/SND)" ///
12 "NVQ LEVEL 4 (OR SNVQ 4) OR HNC/HND (OR SHNC/SHND)" ///
13 "UNIVERSITY CERTIFICATE/ DIPLOMA (NOT DEGREE)" ///
14 "SCOTVEC NATIONAL CERTIFICATE" ///
15 "SCOTBEC/ SCOTEC CERTIFICATE/ DIPLOMA" ///
16 "CLERICAL/ COMMERCIAL (EG. TYPING OR BOOK-KEEPING)" ///
17 "NURSING (EG. SCM, RGN, SRN, SEN)" ///
18 "TEACHING" ///
19 "OTHER PROFESSIONAL (EG. LAW, MEDICINE)" ///
20 "UNIVERSITY OR CNAA DEGREE" ///
21 "MASTERS OR PHD DEGREE" ///
22 "COMPLETION OF TRADE APPRENTICESHIP" ///
23 "PROFESSIONAL QUALIFICATION WITHOUT SITTING EXAM" ///
24 "OTHER" ///
27 "NOT STATED" ///
-2 "REFUSED" ///
-1 "DON'T KNOW" 

label values isco88 isco88lbl
